### ISSUE TITLE
[Feature] Rename 

### ISSUE THREAD

**Issue by polzy** [cglatot/PokeManager#38]
Hi, 
It's possible to rename pokemon like this Pikachu_IV% ?

**Comment by AndikaTanpaH** [comment]
at demo.py line 250
`session.nicknamePokemon(monster[6],str(monster[5]) + '-' + str(monster[2]) + '/' + str(monster[3]) + '/' + str(monster[4]))`

maybe you can edit to
`session.nicknamePokemon(monster[6],str(monster[0])+ ' '+str(monster[5]) + '%' )`

i was try and this my result

> | NAME | CP | ATK | DEF | STA | IV% | Name |
> | --- | --- | --- | --- | --- | --- | --- |
> | BULBASAUR | 596 | 12 | 15 | 14 | 91 |  |
> | CHANSEY | 286 | 15 | 14 | 13 | 93 | CHANSEY 93% |
> | EEVEE | 424 | 15 | 12 | 14 | 91 | EEVEE 91% |
> | EEVEE | 577 | 15 | 15 | 12 | 93 | EEVEE 93% |
> | STARMIE | 1165 | 14 | 15 | 12 | 91 | STARMIE 91% |
> | VAPOREON | 1795 | 15 | 12 | 15 | 93 | VAPOREON 93% |

if you wanna edit log on cmd/terminal you can edit at line 251..
and remember  There is a char limit of 12 for pokemon name. (look at bulbasaur its empty because max char)

**Comment by polzy** [comment]
thanks i try :)

**Comment by cglatot** [comment]
> There is a char limit of 12 for pokemon name

That is exactly why the nicknaming convention is the way it is. It will never be more than 12 chars.
